apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000       # Change from 5000 to 3000
      targetPort: 3000  # Change from 5000 to 3000
  type: LoadBalancer
