apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80      # Port exposé par le service
      targetPort: 3000  # Le port du conteneur (port 3000 défini dans le Dockerfile)
  type: LoadBalancer
