apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: alaakhedhiri/project-frontend
        ports:
        - containerPort: 80  # Ce port est arbitraire car il correspond au port exposé par le service
