apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo-container  # Nom du conteneur, en minuscules
        image: mongo:latest # Ton image MongoDB depuis Docker Hub
        ports:
        - containerPort: 27017  # Port par défaut de MongoDB

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017  # Port par défaut de MongoDB
      targetPort: 27017
      nodePort: 30017  # Exposer MongoDB sur le port 30017 (peut être modifié si nécessaire)
  type: NodePort  # Changer de ClusterIP à NodePort
